apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kure.fullname" . }}-agent
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kure.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kure.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        {{- include "kure.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: agent
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.agent.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: agent
        image: "{{ .Values.global.imageRegistry }}{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
        imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
        env:
        - name: BACKEND_URL
          value: "http://{{ include "kure.fullname" . }}-backend:{{ .Values.backend.service.port }}"
        - name: PYTHONUNBUFFERED
          value: "1"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.agent.resources | nindent 10 }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}