{{- if .Values.backend.env.KURE_LLM_API_KEY }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kure.fullname" . }}-backend-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kure.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  llm-api-key: {{ .Values.backend.env.KURE_LLM_API_KEY | b64enc | quote }}
{{- end }}