{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kure.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kure.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "kure.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}