{{- if not .Values.postgresql.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kure.fullname" . }}-postgresql
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kure.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector:
    {{- include "kure.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql