apiVersion: v1
kind: ServiceAccount
metadata:
  name: kure-backend
  namespace: kure-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kure-frontend
  namespace: kure-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kure-security-scanner
  namespace: kure-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kure-agent
  namespace: kure-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kure-postgresql
  namespace: kure-system
