apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-disallow-host-namespaces
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Disallow Host Namespaces
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Host namespaces (hostNetwork, hostPID, hostIPC) allow containers to access
      host-level resources and must not be allowed. This policy ensures that
      none of these host namespace fields are set to true.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: disallow-host-namespaces
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "Sharing the host namespaces is disallowed. The fields spec.hostNetwork, spec.hostPID, and spec.hostIPC must not be set to true."
      pattern:
        spec:
          =(hostNetwork): "false"
          =(hostPID): "false"
          =(hostIPC): "false"
