apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-disallow-default-namespace
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Disallow Default Namespace
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Kubernetes workloads should not run in the default namespace. This policy
      denies the creation of Pods, Deployments, StatefulSets, DaemonSets, Jobs,
      and CronJobs in the default namespace.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: disallow-default-namespace
    match:
      any:
      - resources:
          kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
          - Job
          - CronJob
          namespaces:
          - default
    {%- if excluded_deployments %}
    exclude:
      any:
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "Resources must not be deployed to the default namespace. Use a dedicated namespace instead."
      deny: {}
