apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-disallow-latest-tag
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The :latest tag is mutable and can lead to unexpected behavior when images
      are updated. This policy requires that container images specify a tag and
      that the tag is not :latest.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: disallow-latest-tag
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "Using the :latest image tag is not allowed. Specify a specific version tag for spec.containers[*].image."
      pattern:
        spec:
          containers:
          - image: "?*:?*"
          =(initContainers):
          - image: "?*:?*"
          =(ephemeralContainers):
          - image: "?*:?*"
  - name: disallow-latest-tag-value
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "The :latest image tag is not allowed. Use a specific version tag instead."
      pattern:
        spec:
          containers:
          - image: "!*:latest"
          =(initContainers):
          - image: "!*:latest"
          =(ephemeralContainers):
          - image: "!*:latest"
