apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-disallow-privilege-escalation
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Privilege escalation, such as via set-user-ID or set-group-ID file mode,
      should not be allowed. This policy ensures that the
      allowPrivilegeEscalation field is set to false on all containers.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: disallow-privilege-escalation
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "Privilege escalation is disallowed. The field spec.containers[*].securityContext.allowPrivilegeEscalation must be set to false."
      pattern:
        spec:
          containers:
          - securityContext:
              allowPrivilegeEscalation: false
          =(initContainers):
          - securityContext:
              allowPrivilegeEscalation: false
          =(ephemeralContainers):
          - securityContext:
              allowPrivilegeEscalation: false
