apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-require-labels
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Require Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Pods should have the standard Kubernetes label app.kubernetes.io/name set
      for proper identification and management. This policy validates that the
      label is present on all Pods.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: require-app-label
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "The label app.kubernetes.io/name is required on all Pods."
      pattern:
        metadata:
          labels:
            app.kubernetes.io/name: "?*"
