apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-require-drop-all-capabilities
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Require Drop All Capabilities
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Containers should drop all Linux capabilities and only add back those that
      are specifically required. This policy ensures that all containers have
      capabilities.drop set to include ALL.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: require-drop-all-capabilities
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "Containers must drop all capabilities. The field spec.containers[*].securityContext.capabilities.drop must include ALL."
      foreach:
      - list: "request.object.spec.containers"
        deny:
          conditions:
            all:
            - key: ALL
              operator: AnyNotIn
              value: "{% raw %}{{ element.securityContext.capabilities.drop || `[]` }}{% endraw %}"
      - list: "request.object.spec.initContainers[]"
        deny:
          conditions:
            all:
            - key: ALL
              operator: AnyNotIn
              value: "{% raw %}{{ element.securityContext.capabilities.drop || `[]` }}{% endraw %}"
      - list: "request.object.spec.ephemeralContainers[]"
        deny:
          conditions:
            all:
            - key: ALL
              operator: AnyNotIn
              value: "{% raw %}{{ element.securityContext.capabilities.drop || `[]` }}{% endraw %}"
