apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-require-liveness-probes
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Require Liveness Probes
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Liveness probes are essential for Kubernetes to detect and restart
      unhealthy containers. This policy validates that all containers have
      a liveness probe defined.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: require-liveness-probes
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "Liveness probes are required for all containers. Set spec.containers[*].livenessProbe."
      pattern:
        spec:
          containers:
          - livenessProbe:
              "?*": "?*"
