apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-require-resource-requests
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Require Resource Requests
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Containers must have resource requests defined for both CPU and memory to
      enable proper scheduling and resource management. This policy validates
      that resource requests are set on all containers.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: require-resource-requests
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "Resource requests are required. Set spec.containers[*].resources.requests.memory and spec.containers[*].resources.requests.cpu."
      pattern:
        spec:
          containers:
          - resources:
              requests:
                memory: "?*"
                cpu: "?*"
