apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-require-readiness-probes
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Require Readiness Probes
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Readiness probes are essential for Kubernetes to know when a container is
      ready to accept traffic. This policy validates that all containers have
      a readiness probe defined.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: require-readiness-probes
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "Readiness probes are required for all containers. Set spec.containers[*].readinessProbe."
      pattern:
        spec:
          containers:
          - readinessProbe:
              "?*": "?*"
