apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-require-resource-limits
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Require Resource Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Containers must have resource limits defined for both CPU and memory to
      prevent resource exhaustion on nodes. This policy validates that resource
      limits are set on all containers.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: require-resource-limits
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "Resource limits are required. Set spec.containers[*].resources.limits.memory and spec.containers[*].resources.limits.cpu."
      pattern:
        spec:
          containers:
          - resources:
              limits:
                memory: "?*"
                cpu: "?*"
