apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kure-restrict-seccomp
  labels:
    app.kubernetes.io/managed-by: kure-monitor
  annotations:
    policies.kyverno.io/title: Restrict Seccomp Profile
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The Seccomp profile must be set to RuntimeDefault or Localhost to restrict
      the syscalls that containers can make. This policy ensures that the
      seccompProfile type is set appropriately at the pod or container level.
spec:
  validationFailureAction: {{ mode }}
  background: true
  rules:
  - name: restrict-seccomp-profile
    match:
      any:
      - resources:
          kinds:
          - Pod
    {%- if excluded_namespaces or excluded_deployments %}
    exclude:
      any:
      {%- for ns in excluded_namespaces %}
      - resources:
          namespaces:
          - "{{ ns }}"
      {%- endfor %}
      {%- for deploy in excluded_deployments %}
      - resources:
          names:
          - "{{ deploy }}*"
      {%- endfor %}
    {%- endif %}
    validate:
      message: "The Seccomp profile must be set to RuntimeDefault or Localhost. Set spec.securityContext.seccompProfile.type accordingly."
      anyPattern:
      - spec:
          securityContext:
            seccompProfile:
              type: "RuntimeDefault"
      - spec:
          securityContext:
            seccompProfile:
              type: "Localhost"
      - spec:
          containers:
          - securityContext:
              seccompProfile:
                type: "RuntimeDefault"
      - spec:
          containers:
          - securityContext:
              seccompProfile:
                type: "Localhost"
