apiVersion: apps/v1
kind: Deployment
metadata:
  name: failed-deploy-image-pull
  namespace: test1
  labels:
    test-case: "image-pull-backoff"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-pull-fail
  template:
    metadata:
      labels:
        app: image-pull-fail
    spec:
      containers:
      - name: app-container
        image: nginxinc/xyz
        ports:
        - containerPort: 8080
