# Test Case 2: Secret Mount Failure - Missing secret
---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
  labels:
    name: test1
---
apiVersion: v1
kind: Pod
metadata:
  name: failed-pod-secret-mount
  namespace: test1
  labels:
    test-case: "secret-mount-failure"
spec:
  containers:
  - name: app-container
    image: nginx:latest
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: missing-secret