# Test Case 2: Secret Mount Failure - Missing secret
---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
  labels:
    name: test1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: failed-pod-secret-mount
  namespace: test1
  labels:
    test-case: "secret-mount-failure"
spec:
  replicas: 1
  selector:
    matchLabels:
      test-case: "secret-mount-failure"
  template:
    metadata:
      labels:
        test-case: "secret-mount-failure"
    spec:
      containers:
      - name: app-container
        image: nginx:latest
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: missing-secret
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: missing-secret
#  namespace: test1
#type: Opaque
#data:
#  key: dGVzdAo=
