# Test Case 5: Resource Limits Exceeded - Insufficient cluster resources
apiVersion: v1
kind: Pod
metadata:
  name: failed-pod-resource-limits
  namespace: default
  labels:
    test-case: "resource-limits-exceeded"
spec:
  containers:
  - name: app-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Gi"
        cpu: "32"
      limits:
        memory: "128Gi" 
        cpu: "64"