# Test Case 9: Service Account Not Found - Missing service account
apiVersion: v1
kind: Pod
metadata:
  name: failed-pod-service-account
  namespace: default
  labels:
    test-case: "service-account-not-found"
spec:
  serviceAccountName: non-existent-service-account
  containers:
  - name: app-container
    image: nginx:latest